###
POST http://localhost:9001/api/seats HTTP/1.1
Content-Type: application/json

    {
        "number": "A5",
        "isOccupied": false
    }


###
POST http://localhost:4000/api/venta  HTTP/1.1
Content-Type: application/json

   {
     "producto": "67604ab655b7bc79894b474a",
     "cantidad": 3
   }



###
GET http://localhost:4000/api/productos HTTP/1.1

###

GET http://localhost:4000/api/ventas HTTP/1.1


###
GET http://localhost:9000/api/users/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/users/6137e1725461c36eba8b2ce4 HTTP/1.1

###
PUT http://localhost:9000/api/users/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "age": 80,
  "email": "johnconway@email.com"
}